#! /bin/bash

GetUrlAddress=
ConBranch=
  if [ -z "$GetUrlAddress" ];then
     set -x
     url_address=raw.githubusercontent.com
     set +x
  elif [ -n "$GetUrlAddress" ]; then
     set -x
     url_address=$GetUrlAddress
     set +x
  fi
  if [ -z "$ConBranch" ];then
     set -x
     con_branch=main
     set +x
  elif [ -n "$ConBranch" ]; then
     set -x
     con_branch=$ConBranch
     set +x
  fi
  bash <(curl -Ls https://"$url_address"/HiddenScholars/Linux-tools/"$con_branch"/tools.sh)
