#! /bin/bash

url_address=
con_branch=
  if [ -z $url_address ];then
     set -x
     url_address=raw.githubusercontent.com
     set +x
  fi
  if [ -z $con_branch ];then
   set -x
   con_branch=main
   set +x
  fi
  bash <(curl -Ls https://$url_address/HiddenScholars/Linux-tools/$con_branch/tools.sh)
